/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Event = IDL.Record({
  'eventId' : IDL.Text,
  'title' : IDL.Text,
  'date' : IDL.Int,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'isUserCreated' : IDL.Bool,
  'location' : IDL.Text,
});
export const ExpenseEntry = IDL.Record({
  'expenseId' : IDL.Text,
  'date' : IDL.Int,
  'notes' : IDL.Text,
  'category' : IDL.Text,
  'amount' : IDL.Float64,
});
export const FuelLog = IDL.Record({
  'cost' : IDL.Float64,
  'date' : IDL.Int,
  'distance' : IDL.Float64,
  'fuelUsed' : IDL.Float64,
});
export const Product = IDL.Record({
  'name' : IDL.Text,
  'sellingPrice' : IDL.Float64,
  'productId' : IDL.Text,
  'currentStock' : IDL.Nat,
});
export const Shift = IDL.Record({
  'startTime' : IDL.Text,
  'status' : IDL.Text,
  'endTime' : IDL.Text,
  'date' : IDL.Int,
  'targetEarnings' : IDL.Float64,
  'notes' : IDL.Text,
  'shiftId' : IDL.Text,
});
export const Sale = IDL.Record({
  'saleId' : IDL.Text,
  'date' : IDL.Int,
  'productName' : IDL.Text,
  'totalAmount' : IDL.Float64,
  'quantity' : IDL.Nat,
});
export const Trip = IDL.Record({
  'date' : IDL.Int,
  'tripId' : IDL.Text,
  'platform' : IDL.Text,
  'durationMinutes' : IDL.Nat,
  'notes' : IDL.Text,
  'amount' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'vehicleName' : IDL.Text,
  'displayName' : IDL.Text,
  'subscriptionTier' : IDL.Nat,
  'voiceEnabled' : IDL.Bool,
  'currencyCode' : IDL.Text,
  'fuelConsumptionRate' : IDL.Float64,
});
export const EarningsGoal = IDL.Record({
  'period' : IDL.Text,
  'targetAmount' : IDL.Float64,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const VoiceUsage = IDL.Record({ 'date' : IDL.Int, 'count' : IDL.Nat });
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCustomEvent' : IDL.Func([Event], [], []),
  'addExpense' : IDL.Func([ExpenseEntry], [], []),
  'addFuelLog' : IDL.Func([FuelLog], [], []),
  'addOrUpdateProduct' : IDL.Func([Product], [], []),
  'addOrUpdateShift' : IDL.Func([Shift], [], []),
  'addSale' : IDL.Func([Sale], [], []),
  'addTrip' : IDL.Func([Trip], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createOrUpdateProfile' : IDL.Func([UserProfile], [], []),
  'deleteCustomEvent' : IDL.Func([IDL.Text], [], []),
  'deleteExpense' : IDL.Func([IDL.Text], [], []),
  'deleteShift' : IDL.Func([IDL.Text], [], []),
  'deleteTrip' : IDL.Func([IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getEarningsGoal' : IDL.Func([], [IDL.Opt(EarningsGoal)], ['query']),
  'getEarningsTotal' : IDL.Func([], [IDL.Float64, IDL.Nat], ['query']),
  'getExpenses' : IDL.Func([], [IDL.Vec(ExpenseEntry)], ['query']),
  'getFuelLogs' : IDL.Func([], [IDL.Vec(FuelLog)], ['query']),
  'getFuelProfile' : IDL.Func(
      [],
      [
        IDL.Record({
          'vehicleName' : IDL.Text,
          'fuelConsumptionRate' : IDL.Float64,
        }),
      ],
      ['query'],
    ),
  'getLowStockProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getSales' : IDL.Func([], [IDL.Vec(Sale)], ['query']),
  'getShiftHistory' : IDL.Func([], [IDL.Vec(Shift)], ['query']),
  'getShifts' : IDL.Func([], [IDL.Vec(Shift)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getTrips' : IDL.Func([], [IDL.Vec(Trip)], ['query']),
  'getUpcomingShifts' : IDL.Func([], [IDL.Vec(Shift)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVoiceUsage' : IDL.Func([], [VoiceUsage], ['query']),
  'incrementVoiceUsage' : IDL.Func([], [IDL.Nat], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveFuelProfile' : IDL.Func([IDL.Float64, IDL.Text], [], []),
  'setEarningsGoal' : IDL.Func([EarningsGoal], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Event = IDL.Record({
    'eventId' : IDL.Text,
    'title' : IDL.Text,
    'date' : IDL.Int,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'isUserCreated' : IDL.Bool,
    'location' : IDL.Text,
  });
  const ExpenseEntry = IDL.Record({
    'expenseId' : IDL.Text,
    'date' : IDL.Int,
    'notes' : IDL.Text,
    'category' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const FuelLog = IDL.Record({
    'cost' : IDL.Float64,
    'date' : IDL.Int,
    'distance' : IDL.Float64,
    'fuelUsed' : IDL.Float64,
  });
  const Product = IDL.Record({
    'name' : IDL.Text,
    'sellingPrice' : IDL.Float64,
    'productId' : IDL.Text,
    'currentStock' : IDL.Nat,
  });
  const Shift = IDL.Record({
    'startTime' : IDL.Text,
    'status' : IDL.Text,
    'endTime' : IDL.Text,
    'date' : IDL.Int,
    'targetEarnings' : IDL.Float64,
    'notes' : IDL.Text,
    'shiftId' : IDL.Text,
  });
  const Sale = IDL.Record({
    'saleId' : IDL.Text,
    'date' : IDL.Int,
    'productName' : IDL.Text,
    'totalAmount' : IDL.Float64,
    'quantity' : IDL.Nat,
  });
  const Trip = IDL.Record({
    'date' : IDL.Int,
    'tripId' : IDL.Text,
    'platform' : IDL.Text,
    'durationMinutes' : IDL.Nat,
    'notes' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'vehicleName' : IDL.Text,
    'displayName' : IDL.Text,
    'subscriptionTier' : IDL.Nat,
    'voiceEnabled' : IDL.Bool,
    'currencyCode' : IDL.Text,
    'fuelConsumptionRate' : IDL.Float64,
  });
  const EarningsGoal = IDL.Record({
    'period' : IDL.Text,
    'targetAmount' : IDL.Float64,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const VoiceUsage = IDL.Record({ 'date' : IDL.Int, 'count' : IDL.Nat });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCustomEvent' : IDL.Func([Event], [], []),
    'addExpense' : IDL.Func([ExpenseEntry], [], []),
    'addFuelLog' : IDL.Func([FuelLog], [], []),
    'addOrUpdateProduct' : IDL.Func([Product], [], []),
    'addOrUpdateShift' : IDL.Func([Shift], [], []),
    'addSale' : IDL.Func([Sale], [], []),
    'addTrip' : IDL.Func([Trip], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createOrUpdateProfile' : IDL.Func([UserProfile], [], []),
    'deleteCustomEvent' : IDL.Func([IDL.Text], [], []),
    'deleteExpense' : IDL.Func([IDL.Text], [], []),
    'deleteShift' : IDL.Func([IDL.Text], [], []),
    'deleteTrip' : IDL.Func([IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getEarningsGoal' : IDL.Func([], [IDL.Opt(EarningsGoal)], ['query']),
    'getEarningsTotal' : IDL.Func([], [IDL.Float64, IDL.Nat], ['query']),
    'getExpenses' : IDL.Func([], [IDL.Vec(ExpenseEntry)], ['query']),
    'getFuelLogs' : IDL.Func([], [IDL.Vec(FuelLog)], ['query']),
    'getFuelProfile' : IDL.Func(
        [],
        [
          IDL.Record({
            'vehicleName' : IDL.Text,
            'fuelConsumptionRate' : IDL.Float64,
          }),
        ],
        ['query'],
      ),
    'getLowStockProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getSales' : IDL.Func([], [IDL.Vec(Sale)], ['query']),
    'getShiftHistory' : IDL.Func([], [IDL.Vec(Shift)], ['query']),
    'getShifts' : IDL.Func([], [IDL.Vec(Shift)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getTrips' : IDL.Func([], [IDL.Vec(Trip)], ['query']),
    'getUpcomingShifts' : IDL.Func([], [IDL.Vec(Shift)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVoiceUsage' : IDL.Func([], [VoiceUsage], ['query']),
    'incrementVoiceUsage' : IDL.Func([], [IDL.Nat], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveFuelProfile' : IDL.Func([IDL.Float64, IDL.Text], [], []),
    'setEarningsGoal' : IDL.Func([EarningsGoal], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };
