/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface EarningsGoal { 'period' : string, 'targetAmount' : number }
export interface Event {
  'eventId' : string,
  'title' : string,
  'date' : bigint,
  'description' : string,
  'category' : string,
  'isUserCreated' : boolean,
  'location' : string,
}
export interface ExpenseEntry {
  'expenseId' : string,
  'date' : bigint,
  'notes' : string,
  'category' : string,
  'amount' : number,
}
export interface FuelLog {
  'cost' : number,
  'date' : bigint,
  'distance' : number,
  'fuelUsed' : number,
}
export interface Product {
  'name' : string,
  'sellingPrice' : number,
  'productId' : string,
  'currentStock' : bigint,
}
export interface Sale {
  'saleId' : string,
  'date' : bigint,
  'productName' : string,
  'totalAmount' : number,
  'quantity' : bigint,
}
export interface Shift {
  'startTime' : string,
  'status' : string,
  'endTime' : string,
  'date' : bigint,
  'targetEarnings' : number,
  'notes' : string,
  'shiftId' : string,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface Trip {
  'date' : bigint,
  'tripId' : string,
  'platform' : string,
  'durationMinutes' : bigint,
  'notes' : string,
  'amount' : number,
}
export interface UserProfile {
  'vehicleName' : string,
  'displayName' : string,
  'subscriptionTier' : bigint,
  'voiceEnabled' : boolean,
  'currencyCode' : string,
  'fuelConsumptionRate' : number,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VoiceUsage { 'date' : bigint, 'count' : bigint }
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCustomEvent' : ActorMethod<[Event], undefined>,
  'addExpense' : ActorMethod<[ExpenseEntry], undefined>,
  'addFuelLog' : ActorMethod<[FuelLog], undefined>,
  'addOrUpdateProduct' : ActorMethod<[Product], undefined>,
  'addOrUpdateShift' : ActorMethod<[Shift], undefined>,
  'addSale' : ActorMethod<[Sale], undefined>,
  'addTrip' : ActorMethod<[Trip], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createOrUpdateProfile' : ActorMethod<[UserProfile], undefined>,
  'deleteCustomEvent' : ActorMethod<[string], undefined>,
  'deleteExpense' : ActorMethod<[string], undefined>,
  'deleteShift' : ActorMethod<[string], undefined>,
  'deleteTrip' : ActorMethod<[string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomEvents' : ActorMethod<[], Array<Event>>,
  'getEarningsGoal' : ActorMethod<[], [] | [EarningsGoal]>,
  'getEarningsTotal' : ActorMethod<[], [number, bigint]>,
  'getExpenses' : ActorMethod<[], Array<ExpenseEntry>>,
  'getFuelLogs' : ActorMethod<[], Array<FuelLog>>,
  'getFuelProfile' : ActorMethod<
    [],
    { 'vehicleName' : string, 'fuelConsumptionRate' : number }
  >,
  'getLowStockProducts' : ActorMethod<[], Array<Product>>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getSales' : ActorMethod<[], Array<Sale>>,
  'getShiftHistory' : ActorMethod<[], Array<Shift>>,
  'getShifts' : ActorMethod<[], Array<Shift>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getTrips' : ActorMethod<[], Array<Trip>>,
  'getUpcomingShifts' : ActorMethod<[], Array<Shift>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVoiceUsage' : ActorMethod<[], VoiceUsage>,
  'incrementVoiceUsage' : ActorMethod<[], bigint>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveFuelProfile' : ActorMethod<[number, string], undefined>,
  'setEarningsGoal' : ActorMethod<[EarningsGoal], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
