/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface EarningsGoal {
    period: string;
    targetAmount: number;
}
export interface Trip {
    date: bigint;
    tripId: string;
    platform: string;
    durationMinutes: bigint;
    notes: string;
    amount: number;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface Event {
    eventId: string;
    title: string;
    date: bigint;
    description: string;
    category: string;
    isUserCreated: boolean;
    location: string;
}
export interface Shift {
    startTime: string;
    status: string;
    endTime: string;
    date: bigint;
    targetEarnings: number;
    notes: string;
    shiftId: string;
}
export interface VoiceUsage {
    date: bigint;
    count: bigint;
}
export interface Sale {
    saleId: string;
    date: bigint;
    productName: string;
    totalAmount: number;
    quantity: bigint;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface FuelLog {
    cost: number;
    date: bigint;
    distance: number;
    fuelUsed: number;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface ExpenseEntry {
    expenseId: string;
    date: bigint;
    notes: string;
    category: string;
    amount: number;
}
export interface Product {
    name: string;
    sellingPrice: number;
    productId: string;
    currentStock: bigint;
}
export interface UserProfile {
    vehicleName: string;
    displayName: string;
    subscriptionTier: bigint;
    voiceEnabled: boolean;
    currencyCode: string;
    fuelConsumptionRate: number;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface StakingRecord {
    stakeId: string;
    icpAmount: number;
    dissolveDelayDays: bigint;
    startDate: bigint;
    notes: string;
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addCustomEvent(event: Event): Promise<void>;
    addExpense(expense: ExpenseEntry): Promise<void>;
    addFuelLog(fuelLog: FuelLog): Promise<void>;
    addOrUpdateProduct(product: Product): Promise<void>;
    addOrUpdateShift(shift: Shift): Promise<void>;
    addSale(sale: Sale): Promise<void>;
    addTrip(trip: Trip): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    createOrUpdateProfile(profile: UserProfile): Promise<void>;
    deleteCustomEvent(eventId: string): Promise<void>;
    deleteExpense(expenseId: string): Promise<void>;
    deleteShift(shiftId: string): Promise<void>;
    deleteTrip(tripId: string): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCustomEvents(): Promise<Array<Event>>;
    getEarningsGoal(): Promise<EarningsGoal | null>;
    getEarningsTotal(): Promise<[number, bigint]>;
    getExpenses(): Promise<Array<ExpenseEntry>>;
    getFuelLogs(): Promise<Array<FuelLog>>;
    getFuelProfile(): Promise<{
        vehicleName: string;
        fuelConsumptionRate: number;
    }>;
    getLowStockProducts(): Promise<Array<Product>>;
    getProducts(): Promise<Array<Product>>;
    getSales(): Promise<Array<Sale>>;
    getShiftHistory(): Promise<Array<Shift>>;
    getShifts(): Promise<Array<Shift>>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getTrips(): Promise<Array<Trip>>;
    getUpcomingShifts(): Promise<Array<Shift>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getVoiceUsage(): Promise<VoiceUsage>;
    incrementVoiceUsage(): Promise<bigint>;
    isCallerAdmin(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    isElevenLabsConfigured(): Promise<boolean>;
    getICPPrice(): Promise<string>;
    getStakingRecords(): Promise<Array<StakingRecord>>;
    saveStakingRecord(record: StakingRecord): Promise<void>;
    deleteStakingRecord(stakeId: string): Promise<void>;
    setElevenLabsApiKey(key: string): Promise<void>;
    elevenLabsTextToSpeech(text: string): Promise<Uint8Array>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveFuelProfile(fuelConsumptionRate: number, vehicleName: string): Promise<void>;
    setEarningsGoal(goal: EarningsGoal): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
}
import type { EarningsGoal as _EarningsGoal, StripeSessionStatus as _StripeSessionStatus, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addCustomEvent(arg0: Event): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCustomEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCustomEvent(arg0);
            return result;
        }
    }
    async addExpense(arg0: ExpenseEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addExpense(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addExpense(arg0);
            return result;
        }
    }
    async addFuelLog(arg0: FuelLog): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addFuelLog(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFuelLog(arg0);
            return result;
        }
    }
    async addOrUpdateProduct(arg0: Product): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrUpdateProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrUpdateProduct(arg0);
            return result;
        }
    }
    async addOrUpdateShift(arg0: Shift): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrUpdateShift(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrUpdateShift(arg0);
            return result;
        }
    }
    async addSale(arg0: Sale): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSale(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSale(arg0);
            return result;
        }
    }
    async addTrip(arg0: Trip): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTrip(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTrip(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createOrUpdateProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrUpdateProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrUpdateProfile(arg0);
            return result;
        }
    }
    async deleteCustomEvent(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCustomEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCustomEvent(arg0);
            return result;
        }
    }
    async deleteExpense(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteExpense(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteExpense(arg0);
            return result;
        }
    }
    async deleteTrip(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTrip(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTrip(arg0);
            return result;
        }
    }
    async deleteShift(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteShift(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteShift(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomEvents(): Promise<Array<Event>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomEvents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomEvents();
            return result;
        }
    }
    async getEarningsGoal(): Promise<EarningsGoal | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getEarningsGoal();
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEarningsGoal();
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEarningsTotal(): Promise<[number, bigint]> {
        if (this.processError) {
            try {
                const result = await this.actor.getEarningsTotal();
                return [
                    result[0],
                    result[1]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEarningsTotal();
            return [
                result[0],
                result[1]
            ];
        }
    }
    async getExpenses(): Promise<Array<ExpenseEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpenses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpenses();
            return result;
        }
    }
    async getFuelLogs(): Promise<Array<FuelLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFuelLogs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFuelLogs();
            return result;
        }
    }
    async getFuelProfile(): Promise<{
        vehicleName: string;
        fuelConsumptionRate: number;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getFuelProfile();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFuelProfile();
            return result;
        }
    }
    async getLowStockProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLowStockProducts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLowStockProducts();
            return result;
        }
    }
    async getProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProducts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProducts();
            return result;
        }
    }
    async getSales(): Promise<Array<Sale>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSales();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSales();
            return result;
        }
    }
    async getShiftHistory(): Promise<Array<Shift>> {
        if (this.processError) {
            try {
                const result = await this.actor.getShiftHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getShiftHistory();
            return result;
        }
    }
    async getShifts(): Promise<Array<Shift>> {
        if (this.processError) {
            try {
                const result = await this.actor.getShifts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getShifts();
            return result;
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTrips(): Promise<Array<Trip>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrips();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrips();
            return result;
        }
    }
    async getUpcomingShifts(): Promise<Array<Shift>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUpcomingShifts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUpcomingShifts();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVoiceUsage(): Promise<VoiceUsage> {
        if (this.processError) {
            try {
                const result = await this.actor.getVoiceUsage();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVoiceUsage();
            return result;
        }
    }
    async incrementVoiceUsage(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.incrementVoiceUsage();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.incrementVoiceUsage();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveFuelProfile(arg0: number, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveFuelProfile(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveFuelProfile(arg0, arg1);
            return result;
        }
    }
    async setEarningsGoal(arg0: EarningsGoal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setEarningsGoal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setEarningsGoal(arg0);
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async isElevenLabsConfigured(): Promise<boolean> {
        const result = await this.actor.isElevenLabsConfigured();
        return result;
    }
    async getICPPrice(): Promise<string> {
        const result = await this.actor.getICPPrice();
        return result;
    }
    async getStakingRecords(): Promise<Array<StakingRecord>> {
        const result = await this.actor.getStakingRecords();
        return result as unknown as Array<StakingRecord>;
    }
    async saveStakingRecord(arg0: StakingRecord): Promise<void> {
        await this.actor.saveStakingRecord(arg0 as unknown as Parameters<typeof this.actor.saveStakingRecord>[0]);
    }
    async deleteStakingRecord(arg0: string): Promise<void> {
        await this.actor.deleteStakingRecord(arg0);
    }
    async setElevenLabsApiKey(arg0: string): Promise<void> {
        await this.actor.setElevenLabsApiKey(arg0);
    }
    async elevenLabsTextToSpeech(arg0: string): Promise<Uint8Array> {
        const result = await this.actor.elevenLabsTextToSpeech(arg0);
        return result;
    }
}
function from_candid_StripeSessionStatus_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_EarningsGoal]): EarningsGoal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n9(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
